### ISSUE TITLE
Allow an authentication-less setup

### ISSUE THREAD

**Issue by robertklep** [scanno/nl.scanno.mqttbroker#2]
I'd like to use MQTT Broker in combination with the [MySensors](https://apps.athom.com/app/org.mysensors.homey) app, so I don't have to run a separate MQTT broker somewhere else.

However, the MySensors app doesn't support authentication.

There's obviously a point to be made that this has to be fixed in MySensors and not in MQTT Broker, but I would still like to be given a choice if I want authentication enabled or not. I realise that this shouldn't be the default setting, but perhaps a checkbox ("allow unauthenticated connections") would be acceptable?

**Comment by scanno** [comment]
Added in the next version.
