### ISSUE TITLE
Broker data failed

### ISSUE THREAD

**Issue by ghost** [scanno/nl.scanno.mqttbroker#4]
After installing the broker i get the following error:
![knipsel](https://user-images.githubusercontent.com/2519741/39265687-35417d20-48c8-11e8-87c8-d976795467bb.PNG)

Running firmware 1.5.9

**Comment by DIYglenn** [comment]
I have this error as well... ENOENT = no file or directory... 

Is it because it is loaded before that 'json' file is generated?

**Comment by scanno** [comment]
@DIYglenn when you start the broker for the first time, that json file is not yet created. The file is created at the moment you add a user that is allowed to connect to the broker.

Perhaps I can add a check in the future to bypass that message.

**Comment by DIYglenn** [comment]
Exactly. That’s what I figured. 
Yeah, I guess either that or initiate an empty file? Or will that maybe create permission issues?
