### ISSUE TITLE
Information in Debug logs

### ISSUE THREAD

**Issue by JHGBaouns** [scanno/nl.scanno.mqttbroker#5]
Hi
When a client in publishing, most of the time the log only say like:
```
Packet published on
Packet published {"POWER":"ON"}
```
I would like to see what client and which topic is published, is it possible to get that?

**Comment by scanno** [comment]
Did you enable the DEBUG log in the broker settings? Because this is what i have in my logging:
20180709-07:51:07 Packet published {"clientId":"xxxxxxx","topic":"owntracks/+/+/event"}
