### ISSUE TITLE
MQTT broker crashing  / not running after upgrading to Beta version 1.0.0

### ISSUE THREAD

**Issue by rvmuilekom69** [scanno/nl.scanno.mqttbroker#8]
Today after upgrading to Beta version 1.0.0 MQTT broker wont run.
Downgrading to stable version is possible, but not compatible with Sonoff 5.12.0 ?

What can i do to make this workable again, or how to downgrade to previous beta version?

Thanks,
Ron

**Comment by scanno** [comment]
Update to 1.0.1 is pending approval that should fix that problem

**Comment by scanno** [comment]
Or if you know how to deal with installing from github, you can manually install the beta branch.

**Comment by rvmuilekom69** [comment]
Hmm never done that (yet).
Do you know when 1.0.1 will be approved/released?

Thanks

**Comment by scanno** [comment]
Well all my apps were approved today, but i guess weejewel is not going  to do that anymore today.

**Comment by scanno** [comment]
@rvmuilekom69 published, thanks to weejewel

**Comment by rvmuilekom69** [comment]
Thanks guys. Great work (and fast 👍)
Lights are working again
